/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task3;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        try {
            // Specify the path to the XML file
            String filePath = "data.xml";

            // Parse XML file
            File xmlFile = new File(filePath);
            if (!xmlFile.exists() || !xmlFile.isFile()) {
                System.out.println("The specified XML file does not exist or is not a file: " + filePath);
                return;
            }

            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
            doc.getDocumentElement().normalize();

            // Check if command-line arguments are provided
            if (args.length == 0) {
                System.out.println("No field numbers provided.");
                return;
            }

            // Validate field numbers
            for (String fieldNumber : args) {
                try {
                    int field = Integer.parseInt(fieldNumber);
                    if (field < 1 || field > 6) {
                        System.out.println("Invalid field number: " + fieldNumber);
                        return;
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Invalid field number: " + fieldNumber);
                    return;
                }
            }

            // Get list of all <record> elements
            NodeList nodeList = doc.getElementsByTagName("record");

            // Initialize ObjectMapper for JSON conversion
            ObjectMapper objectMapper = new ObjectMapper();

            // Create a list to store JSON objects
            List<ObjectNode> jsonList = new ArrayList<>();

            // Convert selected fields to JSON for each record
            for (int temp = 0; temp < nodeList.getLength(); temp++) {
                Node node = nodeList.item(temp);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element = (Element) node;
                    // Create a new JSON object for each record
                    ObjectNode jsonRecord = objectMapper.createObjectNode();
                    for (String fieldNumber : args) {
                        int field = Integer.parseInt(fieldNumber);
                        switch (field) {
                            case 1:
                                jsonRecord.put("Name", getElementTextContent(element, "name"));
                                break;
                            case 2:
                                jsonRecord.put("Postal/Zip", getElementTextContent(element, "postalZip"));
                                break;
                            case 3:
                                jsonRecord.put("Region", getElementTextContent(element, "region"));
                                break;
                            case 4:
                                jsonRecord.put("Country", getElementTextContent(element, "country"));
                                break;
                            case 5:
                                jsonRecord.put("Address", getElementTextContent(element, "address"));
                                break;
                            case 6:
                                jsonRecord.put("List", getElementTextContent(element, "list"));
                                break;
                            default:
                                System.out.println("Invalid field number: " + field);
                        }
                    }
                    // Add the JSON object to the list
                    jsonList.add(jsonRecord);
                }
            }

            // Convert the list of JSON objects to JSON array and print
            String jsonOutput = objectMapper.writeValueAsString(jsonList);
            System.out.println(jsonOutput);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static String getElementTextContent(Element element, String tagName) {
        NodeList nodeList = element.getElementsByTagName(tagName);
        if (nodeList.getLength() > 0 && nodeList.item(0).getNodeType() == Node.ELEMENT_NODE) {
            return nodeList.item(0).getTextContent();
        } else {
            return "N/A"; // Return a default value if the element is missing
        }
    }
}
