/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task3;


import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        try {
            // Specify the path to the XML file
            String filePath = "data.xml";

            // Parse XML file
            File xmlFile = new File(filePath);
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(xmlFile);
            doc.getDocumentElement().normalize();

            // Get list of all <record> elements
            NodeList nodeList = doc.getElementsByTagName("record");

            // Check if command-line arguments are provided
            if (args.length == 0) {
                System.out.println("No field numbers provided.");
                return;
            }

            // Initialize ObjectMapper for JSON conversion
            ObjectMapper objectMapper = new ObjectMapper();

            // Create a list to store JSON objects
            List<ObjectNode> jsonList = new ArrayList<>();

            // Convert selected fields to JSON for each record
            for (int temp = 0; temp < nodeList.getLength(); temp++) {
                Node node = nodeList.item(temp);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element element = (Element) node;
                    // Create a new JSON object for each record
                    ObjectNode jsonRecord = objectMapper.createObjectNode();
                    for (String fieldNumber : args) {
                        int field = Integer.parseInt(fieldNumber);
                        switch (field) {
                            case 1:
                                jsonRecord.put("Name", element.getElementsByTagName("name").item(0).getTextContent());
                                break;
                            case 2:
                                jsonRecord.put("Postal/Zip", element.getElementsByTagName("postalZip").item(0).getTextContent());
                                break;
                            case 3:
                                jsonRecord.put("Region", element.getElementsByTagName("region").item(0).getTextContent());
                                break;
                            case 4:
                                jsonRecord.put("Country", element.getElementsByTagName("country").item(0).getTextContent());
                                break;
                            case 5:
                                jsonRecord.put("Address", element.getElementsByTagName("address").item(0).getTextContent());
                                break;
                            case 6:
                                jsonRecord.put("List", element.getElementsByTagName("list").item(0).getTextContent());
                                break;
                            default:
                                System.out.println("Invalid field number: " + field);
                        }
                    }
                    // Add the JSON object to the list
                    jsonList.add(jsonRecord);
                }
            }

            // Convert the list of JSON objects to JSON array and print
            String jsonOutput = objectMapper.writeValueAsString(jsonList);
            System.out.println(jsonOutput);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
